name: Deploy Material MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs
        run: pip install mkdocs-material

      - name: Fetch and Merge gh-pages
        run: |
          git fetch origin gh-pages:gh-pages || echo "gh-pages branch not found, skipping fetch."
          if git rev-parse --verify gh-pages; then
            git checkout gh-pages
            git merge origin/gh-pages || echo "No changes to merge from remote gh-pages branch."
          else
            git checkout --orphan gh-pages
            echo "Created a new orphan gh-pages branch."
          fi

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --clean --remote-branch gh-pages