name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Step 3: Install MkDocs
      - name: Install MkDocs
        run: pip install mkdocs-material

      # Step 4: Deploy MkDocs to gh-pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --clean --remote-branch gh-pages
