name: Update Changelog

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"          
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+" 
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"  
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
  
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  

      - name: Build Changelog Docker Image
        run: docker build -t changelog-generator -f Dockerfile.changelog .

      - name: Generate Changelog
        run: |
          docker run --rm \
            -e GITHUB_TOKEN=${{ secrets.CHANGELOG_TOKEN }} \
            -v ${{ github.workspace }}:/app \
            changelog-generator -u ${{ github.repository_owner }} -p ${{ github.event.repository.name }}
      
      - name: Debug Git Changes
        run: |
          git status
          git diff --staged

      - name: Push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add CHANGELOG.md
          git diff --cached --quiet || git commit -m "Update changelog for ${{ github.ref_name }}"
          git push https://$GH_TOKEN@github.com/fox-techniques/athena-recruitment-analytics.git update-changelog-${{ github.run_id }}
        env:
          GH_TOKEN: ${{ secrets.CHANGELOG_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f
        with:
          token: ${{ secrets.CHANGELOG_TOKEN }}
          branch: update-changelog-${{ github.run_id }}
          base: main
          title: "Update Changelog for ${{ github.ref_name }}"
          body: "This pull request updates the changelog for release ${{ github.ref_name }}."
          labels: "changelog, automated"
